from django.db import models

class PLangs(models.Model):
    # id autogenerated
	title = models.CharField(max_length=255)
	content = models.TextField(blank=True)
	photo = models.ImageField(upload_to="photos/%Y/%m/%d/")
	time_created = models.DateTimeField(auto_now_add=True)
	time_updated = models.DateTimeField(auto_now=True)
	is_published = models.BooleanField(default=True)
